"use client";

import { useState, useRef, type ReactNode } from "react";
import { useRouter } from "next/navigation";
import { track } from "@vercel/analytics/react";
import { useData } from "@/context/data-context";
import { useLocale } from "@/context/locale-context";
import { Button } from "@/components/ui/button";
import { DownloadReport } from "./download-report";
import type { TranslationKey } from "@/lib/i18n";

const TABS = [
  { key: "overview", labelKey: "tabOverview" as TranslationKey },
  { key: "students", labelKey: "tabStudents" as TranslationKey },
  { key: "growth", labelKey: "tabGrowth" as TranslationKey },
  { key: "trials", labelKey: "tabTrials" as TranslationKey },
  { key: "actions", labelKey: "tabActions" as TranslationKey },
] as const;

type TabKey = (typeof TABS)[number]["key"];

interface DashboardLayoutProps {
  tabs: Record<TabKey, ReactNode>;
  demoBanner?: boolean;
}

export function DashboardLayout({ tabs, demoBanner }: DashboardLayoutProps) {
  const [activeTab, setActiveTab] = useState<TabKey>("overview");
  const [isExporting, setIsExporting] = useState(false);
  const { reset } = useData();
  const { t } = useLocale();
  const router = useRouter();
  const exportRef = useRef<HTMLDivElement>(null);

  const handleReset = () => { reset(); router.push("/#upload"); };

  return (
    <div className="min-h-screen bg-gray-50">
      {demoBanner ? (
        <div className="bg-[hsl(var(--preply-pink-light))] text-center py-2 text-sm">
          {t("demoBanner")}
        </div>
      ) : (
        <div className="bg-emerald-50 text-center py-2 text-sm text-emerald-700 flex items-center justify-center gap-2">
          <svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 15v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2zm10-10V7a4 4 0 00-8 0v4h8z" />
          </svg>
          {t("dashboardPrivacy")}
        </div>
      )}
      <header className="bg-white border-b sticky top-0 z-10">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex items-center justify-between h-16">
            <h1 className="text-xl font-bold font-[family-name:var(--font-dm-sans)]">
              <span className="text-[hsl(var(--preply-pink))]">Preply</span>Pulse
            </h1>
            <div className="flex items-center gap-3">
              <DownloadReport exportRef={exportRef} onExportStateChange={setIsExporting} />
              <Button variant="ghost" size="sm" onClick={handleReset}>{t("uploadNewFile")}</Button>
            </div>
          </div>
          <nav className="flex gap-1 -mb-px">
            {TABS.map((tab) => (
              <button
                key={tab.key}
                onClick={() => { setActiveTab(tab.key); track("tab_clicked", { tab: tab.key }); }}
                className={`px-4 py-3 text-sm font-medium border-b-2 transition-colors ${
                  activeTab === tab.key
                    ? "border-[hsl(var(--preply-pink))] text-[hsl(var(--preply-pink))]"
                    : "border-transparent text-muted-foreground hover:text-foreground"
                }`}
              >
                {t(tab.labelKey)}
              </button>
            ))}
          </nav>
        </div>
      </header>
      <main id="dashboard-content" className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        {tabs[activeTab]}
      </main>

      {isExporting && (
        <div
          ref={exportRef}
          className="absolute left-0 top-0 w-[1200px] bg-white -z-10 opacity-0"
          aria-hidden="true"
        >
          {TABS.map((tab) => (
            <div key={tab.key} className="px-8 py-8">
              <h2 className="text-2xl font-bold font-[family-name:var(--font-dm-sans)] mb-6 pb-3 border-b border-gray-200">
                {t(tab.labelKey)}
              </h2>
              {tabs[tab.key]}
            </div>
          ))}
          <div className="px-8 py-4 text-center text-xs text-gray-300">
            Generated by PreplyPulse
          </div>
        </div>
      )}
    </div>
  );
}
